[package]
name = "chessgraphserver"
version = "0.1.0"
authors = ["etopiei <lj343@icloud.com>"]
edition = "2018"

[dependencies]
iron = "0.6.*"
iron-cors = "0.8.0"
rusted_cypher = "1.1.0"
serde = {version = "1.0.60", features = ["derive"]}
serde_json = "1.0"